version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - '8080'
    ports:
      - '80:8080'
    volumes:
      - ./static:/srv/www/colorboard/static
      - ./docker/nginx/:/etc/nginx/conf.d
    depends_on:
      - python
  python:
    restart: always
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/srv/www/colorboard
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -c gunicorn.py uvik_colorboard.wsgi"
    depends_on:
      - db
  db:
    image: postgres:latest